### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by howy-hw** [xsk666/autopost#14]
用GitHub的Action跑签到类这些据说会被ban诶，后续有没有部署到如云函数之类的，谢谢大佬（〃｀ 3′〃）

**Comment by xsk666** [comment]
我的Action跑了一年多了，都没有被ban😂
腾讯云函数想要的话，有时间可以给你加一个

**Comment by xsk666** [comment]
- [x]  [增加腾讯云函数](../tree/master/main/tencent.py)

**Comment by howy-hw** [comment]
谢谢大佬
