### ISSUE TITLE
学校认证错误

### ISSUE THREAD

**Issue by y1415702869** [xsk666/autopost#18]
好像现在微哨更新了么 必须要退出手机端的微哨才行

**Comment by xsk666** [comment]
我这边都是正常的诶，是不是什么操作错了呢

**Comment by TuAbE** [comment]
确实，要退出手机的微哨

**Comment by xsk666** [comment]
如果方便的话，让我看一下什么情况？  
[打开链接获取QQ](https://base64.us/#d=MzEwNDE4MjE4MA%3D%3D)
