### ISSUE TITLE
微哨的定制化这个怎么搞啊

### ISSUE THREAD

**Issue by LikeAsWind** [xsk666/autopost#19]
微哨的定制化这个怎么搞啊

**Comment by xsk666** [comment]
可以附张图吗

**Comment by LikeAsWind** [comment]
https://lightapp.zit.edu.cn/questionnaire这个是那个打开的父接口 不过找不到对应的登陆接口

**Comment by LikeAsWind** [comment]
![1664795506927 (1)](https://user-images.githubusercontent.com/49971139/193563591-e447a819-08f4-4a8f-9d63-3e69f44f24c7.png)

**Comment by xsk666** [comment]
抱歉忘记回复了，登陆链接[在此](https://api.zit.edu.cn/login)
