### ISSUE TITLE
helper.py存在问题

### ISSUE THREAD

**Issue by haishe0** [xsk666/autopost#2]
登录错误
Traceback (most recent call last):
  File "/main/helper.py", line 91, in <module>
    num.append(str(off(lists, classes[i])))
  File "/main/helper.py", line 66, in off
    "Cookie": cook
NameError: name 'cook' is not defined

**Comment by xsk666** [comment]
这个helper.py我已经放弃维护了（虽然更新时间是最近，但我已经一个多月没有修改了），如果你有需要，可以加我QQ,我来帮你解决一些特殊的问题

**Comment by xsk666** [comment]
为什么放弃呢，有一个故事，有兴趣的话，可以和你说说

**Comment by haishe0** [comment]
可以可以 加你了
