### ISSUE TITLE
代码有问题

### ISSUE THREAD

**Issue by Hwchenxin** [xsk666/autopost#21]
一直显示list index out of range，不对，想问一下怎么解决

**Comment by xsk666** [comment]
麻烦发一下报错截图和traceback

**Comment by Hwchenxin** [comment]
好的稍等



&nbsp;


Dust&nbsp;Heart·（尘心）
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月7日(星期一) 晚上9:11
收件人: ***@***.***&gt;; 
抄送: "Dust ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xsk666/autopost] 代码有问题 (Issue #21)





 
麻烦发一下报错截图和traceback

**Comment by Hwchenxin** [comment]
报错都一样，不知道在哪下手，麻烦告知一下，这么晚打扰了



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xsk666/autopost"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月7日(星期一) 晚上9:11
***@***.***&gt;;
抄送:&nbsp;"Dust ***@***.******@***.***&gt;;
主题:&nbsp;Re: [xsk666/autopost] 代码有问题 (Issue #21)





 
麻烦发一下报错截图和traceback

**Comment by xsk666** [comment]
没有看到报错信息和traceback，麻烦使用github在线回复

**Comment by Hwchenxin** [comment]
图片我发不了

**Comment by xsk666** [comment]
那就发报错的traceback

**Comment by Hwchenxin** [comment]
他这个报错显示
开始为xxx打卡
     xxx打卡失败
然后显示
list index out of range

**Comment by Hwchenxin** [comment]
哥在吗，能帮忙解决一下不，打扰了
&nbsp;


Dust&nbsp;Heart·（尘心）
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月7日(星期一) 晚上9:22
收件人: ***@***.***&gt;; 
抄送: "Dust ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [xsk666/autopost] 代码有问题 (Issue #21)





 
没有看到报错信息和traceback，麻烦使用github在线回复

**Comment by xsk666** [comment]
你的配置文件应该写错了

**Comment by Hwchenxin** [comment]
我就把账号密码加进user.json里面，别的什么都没动

**Comment by xsk666** [comment]
schoolcode改了吗

**Comment by Hwchenxin** [comment]
那个换了

**Comment by Hwchenxin** [comment]
就是相当于domain

**Comment by xsk666** [comment]
请下载代码到本地之后执行，然后告诉我更详细的信息，最好再学一下github的操作，不要...

**Comment by Hwchenxin** [comment]
本地我用pycharm运行了tencent.py文件，我看这个文件是所有文件的综合，然后我添加账号密码学校代码，也显示
开始为xxx打卡
xxx打卡失败
然后显示
list index out of range

**Comment by Hwchenxin** [comment]
因为GitHub上面的错误与pycharm的错误显示一样，所以我就来问一问怎么解决，请教一下问题，并没有什么别的意思

**Comment by xsk666** [comment]
不要运行tencent.py，那是给腾讯云函数用的....，你执行index.py试一下

**Comment by Hwchenxin** [comment]
开始为 xxx 打卡
Traceback (most recent call last):
  File "C:\Users\zkzk\Desktop\autopost-master\main\index.py", line 35, in <module>
    response = post.run(item,cook)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zkzk\Desktop\autopost-master\main\post.py", line 13, in run
    info = getinfo.data(studata, cook)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zkzk\Desktop\autopost-master\main\getinfo.py", line 21, in data
    info = requests.get(url1, headers=head).json().get("data")[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Hwchenxin** [comment]
这个是index.py的显示

**Comment by xsk666** [comment]
这个报错的意思是没有获取到你昨天的打卡信息，你确定学校的打卡界面和我的一样吗

**Comment by Hwchenxin** [comment]
我看那个faild那个图片跟我这个一模一样，但是我看里面的打卡问卷好像不像你发的那个一样，实在不好意思，抱歉

**Comment by Hwchenxin** [comment]
但是你这个写的我看是微哨平台啊，应该没有错吧

**Comment by xsk666** [comment]
打卡内容不一样不重要，主要是界面是不是一样的，不一样的话不能用

**Comment by Hwchenxin** [comment]
那个网站提醒状态500的页面一摸一样的
都是那个wx平台

**Comment by Hwchenxin** [comment]
打卡的图标好像是不一样的

**Comment by xsk666** [comment]
主要看打卡的界面是不是一样的，别的不重要，打卡内容也不重要

**Comment by Hwchenxin** [comment]
打卡的界面好像是提交问卷，不像你的那个

**Comment by xsk666** [comment]
那就不一样

**Comment by Hwchenxin** [comment]
好的，抱歉了，麻烦你了
