### ISSUE TITLE
外校使用

### ISSUE THREAD

**Issue by Standdrinkmilk** [xsk666/autopost#4]
请问大佬，外校要咋用这个啊？

**Comment by xsk666** [comment]
麻烦看看你的学校在不在列表里面的（https://api.weishao.com.cn/login/api/school ）
如果不在的话，此项目不适合你哦

**Comment by Standdrinkmilk** [comment]
在里面呀

**Comment by xsk666** [comment]
好，可以加我QQ，我帮你改一下
