### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by qqilin1213** [xsk666/autopost#5]
如果每一天进入打卡会弹出一个选择框选择是否保留之前写的数据，才能开始打卡，可以用该程序吗

**Comment by xsk666** [comment]
不清楚什么意思呢

**Comment by xsk666** [comment]
你是滁州学院的吗

**Comment by qqilin1213** [comment]
不是，我是外校的，我的意思是我们学校要打卡的时候会有一个提示“是否保留昨天填写的内容”，然后我们才能填写定位，提交这样

**Comment by xsk666** [comment]
可以使用的，看看wiki当中关于外校的介绍

**Comment by qqilin1213** [comment]
OK，谢谢你的解答
