### ISSUE TITLE
dd

### ISSUE THREAD

**Issue by WildboarG** [xsk666/autopost#8]
#甄不错，本来自己打算写呢` 没带电脑在打螺丝，随便看看居然有现成的轮子哈哈
  冒昧的问一下 密码是明文的嘛 不用加密？
   在给你推荐一下pushplus微信推送

**Comment by xsk666** [comment]
这个登陆模块没有问题的，就是自动打卡模块可能会有问题，可以自己去试试，这个仓库好久没有更新了（因为懒）

**Comment by WildboarG** [comment]
问题不大，我在外边打螺丝，过几天回去试试

**Comment by xsk666** [comment]
那我先更新一下（拖了好几个月了）

- [x] 更新自动打卡代码

**Comment by WildboarG** [comment]
孩子崩溃了，抓包分析不出来cookie我们学校的他是自己独立的软件，打卡不能从微哨直接登录，登上去打卡，他会跳转到微哨的打卡的页面，但是获得初始cookie去get登录拿那个ssokey的时候它一直出差emmm

**Comment by xsk666** [comment]
试试这个链接能不能用**https://yq.weishao.com.cn/check/questionnaire**

**Comment by WildboarG** [comment]
带着cookie请求还是没有ssokey

**Comment by WildboarG** [comment]
https://api.zit.edu.cn/login 这是我们学校的，需要带着cookie对它发一次get请求，拿到网页中的ssokey的值，再把ssokey的值带入一次post请求，才能连接上，拿到cookie

**Comment by xsk666** [comment]
<details>
<summary>加我qq，让我试试？</summary>
3104182180
</details>
